
build:
	mkpage csspath=../../css/site.css "title=text:Fountain Demo" content=index.md nav=nav.md ../../page.tmpl > index.html
	mkpage csspath=fountain.css "title=text:An Interview with a Dog" content=interview-with-a-dog.fountain nav=nav.md fountain.tmpl  > interview-with-a-dog.html 
