
build:
	mkpage csspath=../../css/site.css content=index.md nav=nav.md ../../page.tmpl > index.html
	mkpage csspath=fountain.css content=interview-with-a-dog.fountain nav=nav.md fountain.tmpl  > interview-with-a-dog.html 
