name: mkpage # Caltech Library Make Page Project
base: core22 # the base snap is the execution environment for this snap
version: '1.0.1' # Development semver
summary: MkPage provides tools for rendering static websites
description: |
  MkPage Project is a collection of tools for rendering static websites.
  Featured is the mkpage command, a front end to Pandoc (>= v2.10.x).
  Pandoc supports converting from many lightweight markup languages to HTML.
  The mkpage cli supports metadata encoded as JSON front matter, as well as
  additional data sources expressed on the command line in a simple command
  language. Content is rendered using Pandoc's template language.
license: BSD-3-Clause
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict


apps:
  blogit:
    command: bin/blogit
    plugs:
      - home
      - removable-media
  byline:
    command: bin/byline
    plugs:
      - home
      - removable-media
  frontmatter:
    command: bin/frontmatter
    plugs:
      - home
      - removable-media
  mkpage:
    command: bin/mkpage
    plugs:
      - home
      - removable-media
      - network
  mkrss:
    command: bin/mkrss
    plugs:
      - home
      - removable-media
  reldocpath:
    command: bin/reldocpath
    plugs:
      - home
      - removable-media
  sitemapper:
    command: bin/sitemapper
    plugs:
      - home
      - removable-media
  titleline:
    command: bin/titleline
    plugs:
      - home
      - removable-media
  urlencode:
    command: bin/urlencode
    plugs:
      - home
      - removable-media
  urldecode:
    command: bin/urldecode
    plugs:
      - home
      - removable-media
  ws:
    command: bin/ws
    plugs:
      - home
      - removable-media
      - network
  pandoc:
    command: bin/pandoc
    plugs:
      - home
      - removable-media
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib:$SNAP/lib:

parts:
  mkpage:
    plugin: go
    go-channel: stable
    build-environment:
      - "CGO_ENABLED" : "1"
    source-type: git
    source: https://github.com/caltechlibrary/mkpage
  pandoc:
    plugin: nil
    stage-packages:
      - libatomic1
      - pandoc
      - pandoc-data
    organize:
      usr/bin/: bin/
      usr/lib/: lib/
    prime:
      - bin/pandoc
