name: mkpage # Caltech Library Make Page Project
base: core20 # the base snap is the execution environment for this snap
version: '1.0.1' # Development semver
summary: MkPage provides tools for rendering static websites
description: |
  MkPage Project is a collection of tools for rendering static websites.
  Featured is the mkpage command, a front end to Pandoc (>= v2.10.x).
  Pandoc supports converting from many lightweight markup languages to HTML.
  The mkpage cli supports metadata encoded as JSON front matter, as well as
  additional data sources expressed on the command line in a simple command
  language. Content is rendered using Pandoc's template language.
license: BSD-3-Clause
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

layout:
  /usr/share/pandoc:
    bind: $SNAP_DATA/usr/share/pandoc

apps:
  blogit:
    command: bin/blogit
    plugs:
      - home
      - desktop
      - removable-media
    aliases: [blogit]
  byline:
    command: bin/byline
    plugs:
      - home
      - desktop
      - removable-media
    aliases: [byline]
  frontmatter:
    command: bin/frontmatter
    plugs:
      - home
      - desktop
      - removable-media
    aliases: [frontmatter]
  mkpage:
    command: bin/mkpage
    plugs:
      - home
      - desktop
      - removable-media
      - network
    aliases: [mkpage]
  mkrss:
    command: bin/mkrss
    plugs:
      - home
      - desktop
      - removable-media
    aliases: [mkrss]
  reldocpath:
    command: bin/reldocpath
    plugs:
      - home
      - desktop
      - removable-media
    aliases: [reldocpath]
  sitemapper:
    command: bin/sitemapper
    plugs:
      - home
      - desktop
      - removable-media
    aliases: [sitemapper]
  titleline:
    command: bin/titleline
    plugs:
      - home
      - desktop
      - removable-media
    aliases: [titleline]
  urlencode:
    command: bin/urlencode
    plugs:
      - home
      - desktop
      - removable-media
    aliases: [urlencode]
  urldecode:
    command: bin/urldecode
    plugs:
      - home
      - desktop
      - removable-media
    aliases: [urldecode]
  ws:
    command: bin/ws
    plugs:
      - home
      - desktop
      - removable-media
      - network
    aliases: [ws]
  pandoc:
    command: bin/pandoc
    plugs:
      - home
      - desktop
      - removable-media
    aliases: [pandoc]

parts:
  mkpage:
    plugin: go
    go-channel: stable
    build-environment:
      - "CGO_ENABLED" : "1"
    source-type: git
    source: https://github.com/caltechlibrary/mkpage
    organize:
      usr/lib/: lib/
      usr/share/: share/
  libatomic1:
    plugin: nil
    stage-packages:
      - libatomic1
    organize:
      usr/lib/: lib/
      usr/share/: share/
  pandoc-data:
    plugin: nil
    stage-packages:
      - pandoc-data
    organize:
      usr/lib/: lib/
      usr/share/: share/
      usr/share/pandoc/: share/pandoc/
      usr/share/pandoc/data/: share/pandoc/data/
      usr/share/pandoc/data/templates/: share/pandoc/data/templates/
  pandoc:
    plugin: nil
    stage-packages:
      - libatomic1
      - pandoc
      - pandoc-data
    organize:
      usr/bin/: bin/
      usr/lib/: lib/
      usr/share/: share/
      usr/share/pandoc/: share/pandoc/
      usr/share/pandoc/data/: share/pandoc/data/
      usr/share/pandoc/data/templates/: share/pandoc/data/templates/
    prime:
      - bin/pandoc
